version: '3'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    # restart: always
    # command: mongod --noauth --smallfiles
    ports:
      - "27017:27017"
    networks:
      - webappnetwork
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "3001:5000"
    volumes:
      - ./server:/app
    networks:
      - webappnetwork
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"

networks:
  webappnetwork:
    driver: bridge